# Generated by Django 5.1.3 on 2024-11-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GN', 'general'), ('ER', 'error'), ('WN', 'warning'), ('LK', 'lock'), ('OP', 'operation'), ('CF', 'config')], default='GN', max_length=2)),
                ('content', models.CharField(max_length=200)),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
