# Generated by Django 5.1.3 on 2024-11-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='occured_at',
            new_name='occurred_at',
        ),
    ]
