# Generated by Django 5.1.3 on 2025-12-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_occured_at_event_occurred_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('GN', 'general'), ('WN', 'warning'), ('ER', 'error'), ('US', 'user'), ('OP', 'operation'), ('ST', 'setting'), ('PD', 'pid'), ('LK', 'lock'), ('CF', 'config')], default='GN', max_length=2),
        ),
    ]
