# Generated by Django 5.1.3 on 2025-12-01 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0002_rename_team_channel_teams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PidOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pid_operation_history', to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pid_operation_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
