# Generated by Django 5.1.3 on 2024-11-11 05:29

import django.db.models.deletion
import lock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=lock.models.get_default_expires_at)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lock_history', to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
