# Generated by Django 5.1.3 on 2024-11-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE setting_setting ALTER COLUMN exposure TYPE INTERVAL USING (exposure * INTERVAL '1 second');",
            reverse_sql='ALTER TABLE setting_setting ALTER COLUMN exposure TYPE DOUBLE PRECISION USING (extract(epoch from exposure));'
        ),
        migrations.AlterField(
            model_name='setting',
            name='exposure',
            field=models.DurationField(),
        ),
    ]
