# Generated by Django 5.1.3 on 2024-11-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('team', models.ManyToManyField(related_name='channels', to='team.team')),
            ],
        ),
    ]
