# Generated by Django 5.1.3 on 2024-11-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='team',
            new_name='teams',
        ),
    ]
