# Generated by Django 5.1.3 on 2025-12-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_rename_team_channel_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='dac_channel',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
