# Generated by Django 5.1.3 on 2025-12-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_dac_channel'),
        ('dac_device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='dac_device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channels', to='dac_device.dacdevice'),
        ),
    ]
