# Generated by Django 5.1.3 on 2026-02-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channel_dac_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='max_exposure',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
