# Generated by Django 5.1.3 on 2024-11-12 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measure_history', to='setting.setting')),
            ],
        ),
    ]
