# Generated by Django 5.1.3 on 2024-11-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='error',
            field=models.CharField(choices=[('under', 'underexposed'), ('over', 'overexposed')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='frequency',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
