# Generated by Django 5.1.3 on 2025-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_measurement_error_alter_measurement_frequency'),
        ('setting', '0002_alter_setting_exposure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measured_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['setting', 'measured_at'], name='measurement_setting_43ec3a_idx'),
        ),
    ]
