# Generated by Django 5.1.3 on 2024-11-11 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wlm_version', models.IntegerField(default=None, null=True)),
                ('wlm_dll_path', models.CharField(default=None, max_length=100, null=True)),
                ('wlm_app_path', models.CharField(default=None, max_length=100, null=True)),
                ('calib_ch', models.IntegerField()),
                ('calib_freq', models.FloatField()),
                ('lock_duration', models.DurationField(default=datetime.timedelta(seconds=300))),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id',), name='unique_config')],
            },
        ),
    ]
