# Generated by Django 5.1.3 on 2024-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='wlm_app_path',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='wlm_dll_path',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='wlm_version',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
