# Generated by Django 5.1.3 on 2024-11-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_config_wlm_app_path_alter_config_wlm_dll_path_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='config',
            name='unique_config',
        ),
        migrations.AddConstraint(
            model_name='config',
            constraint=models.CheckConstraint(condition=models.Q(('id__gt', 1), _negated=True), name='unique_config'),
        ),
    ]
