# Generated by Django 5.1.3 on 2024-11-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_config_unique_config_config_unique_config'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='config',
            name='unique_config',
        ),
    ]
