# Generated by Django 5.1.3 on 2024-11-26 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_config_unique_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='calib_exposure',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
            preserve_default=False,
        ),
    ]
