# Generated by Django 5.1.3 on 2025-12-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_config_calib_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='dac_com_port',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
