# Generated by Django 5.1.3 on 2025-12-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_config_dac_com_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='dac_com_port',
        ),
    ]
