# Generated by Django 5.1.3 on 2025-12-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_remove_config_dac_com_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='calib_exposure',
        ),
    ]
