# Generated by Django 5.1.3 on 2025-12-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DacDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('backed', models.CharField(choices=[('DAC8734', 'DAC8734')], default='DAC8734', max_length=30)),
                ('port', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
