# Generated by Django 5.1.3 on 2025-12-15 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dac_device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dacdevice',
            old_name='backed',
            new_name='backend',
        ),
    ]
