# Generated by Django 5.1.3 on 2025-12-02 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0002_rename_team_channel_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='PidSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_frequency', models.FloatField()),
                ('kp', models.FloatField()),
                ('ki', models.FloatField()),
                ('kd', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pid_setting_history', to='channel.channel')),
            ],
        ),
    ]
