# Generated by Django 5.1.3 on 2025-12-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channel_dac_device'),
        ('pid_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DacVoltage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dac_voltage_history', to='channel.channel')),
            ],
        ),
    ]
